name       : yapf
version    : 0.32.0
release    : 7
source     :
    - https://github.com/google/yapf/archive/refs/tags/v0.32.0.tar.gz : 410ed0f592c898d75d73f7792aee6569bdbc0b57bc72b417c722c17f41f66b12
homepage   : https://github.com/google/yapf
license    : Apache-2.0
component  : programming.tools
summary    : A formatter for Python files
description: |
    A formatter for Python files. The ultimate goal is that the code YAPF produces is as good as the code that a programmer would write if they were following the style guide. It takes away some of the drudgery of maintaining your code.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
