name       : yapf
version    : 0.29.0
release    : 3
source     :
    - https://github.com/google/yapf/archive/v0.29.0.tar.gz : f4bc9924de51d30da0241503d56e9e26a1a583bc58b3a13b2c450c4d16c9920d
license    : Apache-2.0
component  : programming.tools
summary    : A formatter for Python files
description: |
    A formatter for Python files.

    The ultimate goal is that the code YAPF produces is as good as the code that a programmer would write if they were following the style guide. It takes away some of the drudgery of maintaining your code.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
