name       : yapf
version    : 0.30.0
release    : 6
source     :
    - https://github.com/google/yapf/archive/v0.30.0.tar.gz : 9f561af26f8d27c3a334d3d2ee8947b8826a86691087e447ce483512d834682c
license    : Apache-2.0
component  : programming.tools
summary    : A formatter for Python files
description: |
    A formatter for Python files.

    The ultimate goal is that the code YAPF produces is as good as the code that a programmer would write if they were following the style guide. It takes away some of the drudgery of maintaining your code.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
